version: "3.8"

services:
  postgres:
    image: postgres
    container_name: phd_student_control_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432